# Generated by Django 5.0.14 on 2026-07-07 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agencies',
            },
        ),
    ]
