# Generated by Django 5.0.14 on 2026-07-07 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('GROUP_VISA', 'Group Visa'), ('INDIVIDUAL_VISA', 'Individual Visa'), ('AIR_TICKET', 'Air Ticket')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='agencies.agency')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='air_ticket_details', serialize=False, to='travel_requests.baserequest')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('passengers', models.IntegerField()),
                ('preferred_airline', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'air_tickets',
            },
        ),
        migrations.CreateModel(
            name='GroupVisa',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='group_visa_details', serialize=False, to='travel_requests.baserequest')),
                ('number_of_passengers', models.IntegerField()),
                ('flight_itinerary', models.TextField()),
                ('flight_code', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('country_code', models.CharField(max_length=10)),
                ('group_leader_name', models.CharField(max_length=255)),
                ('india_number', models.CharField(max_length=50)),
                ('saudi_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'group_visas',
            },
        ),
    ]
