# Generated by Django 5.0.14 on 2026-07-12 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualVisa',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual_visa_details', serialize=False, to='travel_requests.baserequest')),
                ('visa_subtype', models.CharField(choices=[('NORMAL', 'Normal Visa'), ('IQAMA', 'Iqama Visa')], default='NORMAL', max_length=10)),
                ('number_of_passengers', models.IntegerField(default=1)),
                ('arrival_flight', models.CharField(blank=True, default='', max_length=255)),
                ('departure_flight', models.CharField(blank=True, default='', max_length=255)),
                ('stay_days', models.IntegerField(default=1)),
                ('saudi_number', models.CharField(blank=True, default='', max_length=50)),
                ('india_number', models.CharField(blank=True, default='', max_length=50)),
                ('iqama_holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('iqama_id', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_address', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'individual_visas',
            },
        ),
        migrations.AlterModelOptions(
            name='baserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='airticket',
            name='luggage_weight',
            field=models.IntegerField(blank=True, help_text='Weight in KG', null=True),
        ),
        migrations.AddField(
            model_name='airticket',
            name='meal_preference',
            field=models.CharField(choices=[('NONE', 'No Preference'), ('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('HALAL', 'Halal')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='airticket',
            name='wheelchair_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='preferred_airline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='travel_requests.baserequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah')], max_length=10)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('QUAD', 'Quad'), ('PENTAGONAL', 'Pentagonal'), ('HEXAGONAL', 'Hexagonal')], max_length=20)),
                ('room_count', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('group_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel_requests.groupvisa')),
            ],
            options={
                'db_table': 'hotel_details',
            },
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('AIRPORT_PICKUP', 'Airport Pickup'), ('MAKKAH_ZIYARAH', 'Makkah Ziyarah'), ('MAKKAH_TO_MADINAH', 'Makkah to Madinah'), ('MADINAH_ZIYARAH', 'Madinah Ziyarah / Rawdah')], max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('period', models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2)),
                ('group_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='travel_requests.groupvisa')),
            ],
            options={
                'db_table': 'transport_details',
            },
        ),
    ]
