# Generated by Django 5.0.14 on 2026-07-19 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0004_attachment_file_alter_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('passport_expiry', models.DateField()),
                ('is_lead', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='travel_requests.baserequest')),
            ],
            options={
                'db_table': 'passengers',
                'ordering': ['-is_lead', 'full_name'],
            },
        ),
    ]
