# Generated by Django 5.0.14 on 2026-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0006_alter_baserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticket',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INCOMPLETE', 'Incomplete'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='flight_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='flight_itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='group_leader_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='india_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='number_of_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='saudi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupvisa',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='city',
            field=models.CharField(blank=True, choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='room_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetail',
            name='room_type',
            field=models.CharField(blank=True, choices=[('QUAD', 'Quad'), ('PENTAGONAL', 'Pentagonal'), ('HEXAGONAL', 'Hexagonal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='period',
            field=models.CharField(blank=True, choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('AIRPORT_PICKUP', 'Airport Pickup'), ('MAKKAH_ZIYARAH', 'Makkah Ziyarah'), ('MAKKAH_TO_MADINAH', 'Makkah to Madinah'), ('MADINAH_ZIYARAH', 'Madinah Ziyarah / Rawdah')], max_length=30, null=True),
        ),
    ]
