# Generated by Django 5.0.14 on 2026-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0007_alter_airticket_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT_FRONT', 'Passport Front'), ('PASSPORT_BACK', 'Passport Back'), ('PHOTO', 'Photograph'), ('TICKET', 'Flight Ticket'), ('VISA', 'Visa Copy'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
