# Generated by Django 5.0.14 on 2026-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0008_attachment_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserequest',
            name='current_phase',
            field=models.IntegerField(default=1),
        ),
    ]
