# Generated by Django 5.0.14 on 2026-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0010_passenger_passport_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
